# Generated by Django 5.0.14 on 2025-08-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_userprogress_selected_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='selected_option',
        ),
    ]
