# Generated by Django 5.0.14 on 2025-08-25 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_userprogress_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_app.option'),
        ),
    ]
